// <auto-generated />
using CharacterStorage.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CharacterStorage.Migrations
{
    [DbContext(typeof(CharacterStorageContext))]
    [Migration("20200625183707_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CharacterStorage.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bio");

                    b.Property<int>("Echo");

                    b.Property<int>("Experience");

                    b.Property<string>("Faction");

                    b.Property<int>("Fortune");

                    b.Property<int>("Judgement");

                    b.Property<int>("Level");

                    b.Property<int>("Magnetism");

                    b.Property<int>("Might");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Spryness");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Bio = "Driven to drink by mediocrity.",
                            Echo = 8,
                            Experience = 0,
                            Fortune = 15,
                            Judgement = 6,
                            Level = 2,
                            Magnetism = 9,
                            Might = 10,
                            Name = "Garrick",
                            Spryness = 12
                        },
                        new
                        {
                            CharacterId = 2,
                            Bio = "Small business owner.",
                            Echo = 15,
                            Experience = 0,
                            Fortune = 1,
                            Judgement = 1,
                            Level = 5,
                            Magnetism = 15,
                            Might = 15,
                            Name = "Nori",
                            Spryness = 15
                        },
                        new
                        {
                            CharacterId = 3,
                            Bio = "A small dragon in a big body",
                            Echo = 1,
                            Experience = 0,
                            Fortune = 6,
                            Judgement = 15,
                            Level = 10,
                            Magnetism = 8,
                            Might = 25,
                            Name = "Ulstyr",
                            Spryness = 10
                        },
                        new
                        {
                            CharacterId = 4,
                            Bio = "Brian made this guy and he is a stupid idiot",
                            Echo = 8,
                            Experience = 0,
                            Fortune = 15,
                            Judgement = 6,
                            Level = 2,
                            Magnetism = 9,
                            Might = 1,
                            Name = "Larry",
                            Spryness = 6
                        },
                        new
                        {
                            CharacterId = 5,
                            Bio = "Brian made this guy and he is a stupid idiot",
                            Echo = 44,
                            Experience = 0,
                            Fortune = 1,
                            Judgement = 1,
                            Level = 5,
                            Magnetism = 44,
                            Might = 4,
                            Name = "Robert Smith",
                            Spryness = 44
                        },
                        new
                        {
                            CharacterId = 6,
                            Bio = "Brian made this guy and he is a stupid idiot",
                            Echo = 1,
                            Experience = 0,
                            Fortune = 6,
                            Judgement = 15,
                            Level = 9,
                            Magnetism = 8,
                            Might = 9,
                            Name = "Farts",
                            Spryness = 9
                        },
                        new
                        {
                            CharacterId = 7,
                            Bio = "Brian made this guy and he is a stupid idiot",
                            Echo = 8,
                            Experience = 0,
                            Fortune = 15,
                            Judgement = 19,
                            Level = 2,
                            Magnetism = 9,
                            Might = 6,
                            Name = "Cuck Fucker",
                            Spryness = 19
                        },
                        new
                        {
                            CharacterId = 8,
                            Bio = "Brian made this guy and he is a stupid idiot",
                            Echo = 15,
                            Experience = 0,
                            Fortune = 1,
                            Judgement = 1,
                            Level = 5,
                            Magnetism = 15,
                            Might = 400,
                            Name = "Wage cuck",
                            Spryness = 15
                        },
                        new
                        {
                            CharacterId = 9,
                            Bio = "Brian made this guy and he is a stupid idiot",
                            Echo = 1,
                            Experience = 0,
                            Fortune = 16,
                            Judgement = 15,
                            Level = 6,
                            Magnetism = 8,
                            Might = 55,
                            Name = "Orc",
                            Spryness = 6
                        },
                        new
                        {
                            CharacterId = 10,
                            Bio = "Brian made this guy and he is a stupid idiot",
                            Echo = 8,
                            Experience = 0,
                            Fortune = 15,
                            Judgement = 6,
                            Level = 2,
                            Magnetism = 6,
                            Might = 16,
                            Name = "Elf",
                            Spryness = 6
                        },
                        new
                        {
                            CharacterId = 21,
                            Bio = "Brian made this guy and he is a stupid idiot",
                            Echo = 90,
                            Experience = 0,
                            Fortune = 1,
                            Judgement = 1,
                            Level = 5,
                            Magnetism = 90,
                            Might = 90,
                            Name = "Boy",
                            Spryness = 90
                        },
                        new
                        {
                            CharacterId = 31,
                            Bio = "Hail Stan",
                            Echo = 666,
                            Experience = 0,
                            Fortune = 666,
                            Judgement = 666,
                            Level = 666,
                            Magnetism = 666,
                            Might = 666,
                            Name = "Gnome",
                            Spryness = 666
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
